/// Flutter icons Sports
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Sports
///      fonts:
///       - asset: fonts/Sports.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class NearbyFriendlyMatch {

  const NearbyFriendlyMatch({this.icon, this.image, this.title, this.location, this.players});

  final Image image;
  final String title;
  final String location;
  final String players;
  final Icon icon;



}
