/// Flutter icons Sports
/// Copyright (C) 2018 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Sports
///      fonts:
///       - asset: fonts/Sports.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
///
import 'package:flutter/widgets.dart';

class Sports {
  Sports._();

  static const _kFontFam = 'Sports';

  static const IconData baseball = const IconData(0xe806, fontFamily: _kFontFam);
  static const IconData basketball = const IconData(0xe807, fontFamily: _kFontFam);
  static const IconData cricket = const IconData(0xe813, fontFamily: _kFontFam);
  static const IconData golf = const IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData soccer = const IconData(0xe837, fontFamily: _kFontFam);
  static const IconData swimming = const IconData(0xe838, fontFamily: _kFontFam);
  static const IconData tennis = const IconData(0xe839, fontFamily: _kFontFam);
}
